SELECT
CS.PROCESSDEFINITIONID AS CS_PROCESS_DEFINITION_ID,
CS.NAME AS CS_NAME,
CS.STATEID AS CS_STATE_ID,
CS.STARTDATE AS CS_START_DATE,
CS.ID AS CS_ID,
0 AS CS_SOURCEOBJECTID,
APS.PROCESSID AS APS_PROCESS_ID,
APS.NAME AS APS_NAME,
USR.FIRSTNAME AS USR_FIRSTNAME,
USR.LASTNAME AS USR_LASTNAME
FROM process_instance CS
INNER JOIN process_definition APS ON CS.PROCESSDEFINITIONID = APS.PROCESSID
INNER JOIN user_ USR ON CS.STARTEDBY = USR.ID
WHERE CS.TENANTID = 1
AND APS.TENANTID = 1
AND USR.TENANTID = 1
AND CS.STATEID = 6
AND CS.STARTDATE BETWEEN 1369173600470 AND 1369864799470
AND APS.PROCESSID = 1
UNION
SELECT
CS.PROCESSDEFINITIONID AS CS_PROCESS_DEFINITION_ID,
CS.NAME AS CS_NAME,
CS.STATEID AS CS_STATE_ID,
CS.STARTDATE AS CS_START_DATE,
CS.ID AS CS_ID,
0 AS CS_SOURCEOBJECTID,
APS.PROCESSID AS APS_PROCESS_ID,
APS.NAME AS APS_NAME,
'System' AS USR_FIRSTNAME,
'' AS USR_LASTNAME
FROM process_instance CS
INNER JOIN process_definition APS ON CS.PROCESSDEFINITIONID = APS.PROCESSID
WHERE CS.TENANTID = 1
AND APS.TENANTID = 1
AND CS.STARTEDBY = 0
AND CS.STATEID = 6
AND CS.STARTDATE BETWEEN 1369173600470 AND 1369864799470
AND APS.PROCESSID = 1
UNION
SELECT
CS.PROCESSDEFINITIONID AS CS_PROCESS_DEFINITION_ID,
CS.NAME AS CS_NAME,
CS.STATEID AS CS_STATE_ID,
CS.STARTDATE AS CS_START_DATE,
CS.ID AS CS_ID,
CS.SOURCEOBJECTID AS CS_SOURCEOBJECTID,
APS.PROCESSID AS APS_PROCESS_ID,
APS.NAME AS APS_NAME,
USR.FIRSTNAME AS USR_FIRSTNAME,
USR.LASTNAME AS USR_LASTNAME
FROM arch_process_instance  CS
INNER JOIN process_definition APS ON CS.PROCESSDEFINITIONID = APS.PROCESSID
INNER JOIN user_ USR ON CS.STARTEDBY = USR.ID
WHERE CS.ENDDATE > 0
AND CS.TENANTID = 1
AND APS.TENANTID = 1
AND USR.TENANTID = 1
AND CS.STATEID = 6
AND CS.STARTDATE BETWEEN 1369173600470 AND 1369864799470
AND APS.PROCESSID = 1
UNION
SELECT
CS.PROCESSDEFINITIONID AS CS_PROCESS_DEFINITION_ID,
CS.NAME AS CS_NAME,
CS.STATEID AS CS_STATE_ID,
CS.STARTDATE AS CS_START_DATE,
CS.ID AS CS_ID,
CS.SOURCEOBJECTID AS CS_SOURCEOBJECTID,
APS.PROCESSID AS APS_PROCESS_ID,
APS.NAME AS APS_NAME,
'System' AS USR_FIRSTNAME,
'' AS USR_LASTNAME
FROM arch_process_instance  CS
INNER JOIN process_definition APS ON CS.PROCESSDEFINITIONID = APS.PROCESSID
WHERE CS.ENDDATE > 0
AND CS.TENANTID = 1
AND APS.TENANTID = 1
AND CS.STARTEDBY = 0
AND CS.STATEID = 6
AND CS.STARTDATE BETWEEN 1369173600470 AND 1369864799470
AND APS.PROCESSID = 1