SELECT
    CS.PROCESSDEFINITIONID AS CS_PROCESS_DEFINITION_ID,
    CS.NAME AS CS_NAME,
    CS.STATEID AS CS_STATE_ID,
    CS.STARTDATE AS CS_START_DATE,
    (FLOOR(CS.STARTDATE/86400000)) as CS_START,
    CS.ENDDATE AS CS_END_DATE,
    (FLOOR(CS.ENDDATE/86400000)) as CS_END,
    CS.ID AS CS_ID,
    CS.SOURCEOBJECTID AS CS_SOURCEOBJECTID,
    APS.PROCESSID AS APS_PROCESS_ID,
    APS.NAME AS APS_NAME,
    USR.FIRSTNAME AS USR_FIRSTNAME,
    USR.LASTNAME AS USR_LASTNAME,
    ( CS.ENDDATE - CS.STARTDATE ) AS CS_DURATION
FROM arch_process_instance  CS
INNER JOIN process_definition APS ON CS.PROCESSDEFINITIONID = APS.PROCESSID
INNER JOIN user_ USR ON CS.STARTEDBY = USR.ID
WHERE CS.ENDDATE > 0
AND CS.TENANTID = 1
AND APS.TENANTID = 1
AND USR.TENANTID = 1
AND CS.ENDDATE BETWEEN 1369173600470 AND 1369864799470
AND APS.PROCESSID = 1
ORDER BY 14 DESC, 6, 4