SELECT
        GLOBAL_TABLE.CASE_ID,
        GLOBAL_TABLE.ROOT_CASE_ID,
        GLOBAL_TABLE.CASE_START_DATE,
        GLOBAL_TABLE.CASE_STARTED_BY_FIRSTNAME,
        GLOBAL_TABLE.CASE_STARTED_BY_LASTNAME,
        GLOBAL_TABLE.CASE_STATE_ID,
        GLOBAL_TABLE.CASE_ARCHIVED_ON
        FROM
        (
            SELECT
                CS.STATEID AS CASE_STATE_ID,
                CS.STARTDATE AS CASE_START_DATE,
                CS.ID AS CASE_ID,
                CS.ROOTPROCESSINSTANCEID AS ROOT_CASE_ID,
        0 AS CASE_ARCHIVED_ON,
                CS_USR.FIRSTNAME AS CASE_STARTED_BY_FIRSTNAME,
                CS_USR.LASTNAME AS CASE_STARTED_BY_LASTNAME
            FROM process_instance CS
            LEFT JOIN user_ CS_USR
        ON CS.STARTEDBY = CS_USR.ID
        AND CS.TENANTID = CS_USR.TENANTID
            WHERE CS.TENANTID = 1
    AND PROCESSDEFINITIONID = 1
    AND CS.ID = 1
    AND CS.STARTDATE <= 1369864799470

    UNION

            SELECT
                 CS.STATEID AS CASE_STATE_ID,
                CS.STARTDATE AS CASE_START_DATE,
                CS.SOURCEOBJECTID AS CASE_ID,
                CS.ROOTPROCESSINSTANCEID AS ROOT_CASE_ID,
        CS.ARCHIVEDATE AS CASE_ARCHIVED_ON,
                CS_USR.FIRSTNAME AS CASE_STARTED_BY_FIRSTNAME,
                CS_USR.LASTNAME AS CASE_STARTED_BY_LASTNAME
            FROM arch_process_instance  CS
      LEFT JOIN user_ CS_USR
        ON CS.STARTEDBY = CS_USR.ID
        AND CS.TENANTID = CS_USR.TENANTID
            WHERE CS.TENANTID = 1
    AND PROCESSDEFINITIONID = 1
    AND CS.SOURCEOBJECTID =  1
          AND CS.ENDDATE >= 1369173600470
    AND CS.STARTDATE <= 1369864799470

        ) GLOBAL_TABLE
        ORDER BY GLOBAL_TABLE.CASE_START_DATE, GLOBAL_TABLE.ROOT_CASE_ID, GLOBAL_TABLE.CASE_ID