class Deps {

    public static String springVersion = "5.1.5.RELEASE"
    public static String springBootVersion = "2.1.3.RELEASE"
    public static String commonsCodecVersion = "1.7"
    public static String commonsIOVersion = "2.5"
    public static String commonsBeanutilsVersion = "1.9.2"
    public static String commonsCollectionsVersion = "3.2.2"
    public static String commonsCollections4Version = "4.0"
    public static String commonsLangVersion = "3.3.2"
    public static String commonsDbcp2Version = "2.5.0"
    public static String commonsDbcpVersion = "1.4"
    public static String commonsExecVersion = "1.3"
    public static String commonsCLIVersion = "1.2"
    public static String commonsPoolVersion = "1.5.5"
    public static String slf4jVersion = "1.7.25"
    public static String h2Version = "1.3.175"
    public static String hibernateVersion = "4.3.11.Final"
    public static String jacksonDataBindingVersion = "2.9.8"
    public static String javaxJtaVersion = "1.1"
    public static String groovyAllVersion = "2.4.16"
    public static String javassistVersion = "3.18.1-GA"
    public static String httpComponentsVersion = "4.5.2"
    public static String xstreamVersion = "1.4.10"
    public static String hibernateJpaVersion = "1.0.0.Final"
    public static String ehcacheVersion = "2.4.7"
    public static String eclipseCompilerVersion = "4.6.1"
    public static String jbcryptVersion = "0.3m"
    public static String javaxActivationVersion = "1.1.1"
    public static String quartzVersion = "2.2.1"
    public static String guavaVersion = "19.0"

    public static String mysqlVersion = "8.0.14"
    public static String mssqlVersion = "7.2.1.jre8"
    public static String oracleVersion = "8.12.2.0.1"
    public static String postgresqlVersion = "42.2.5"
    public static String lombokVersion = "1.18.4"

    public static String naranayaVersion = "5.9.3.Final"
    public static String jbossLoggingVersion = "3.1.3.GA"
    public static String jaxbVersion = "2.2.7"
    public static String logbackVersion = "1.2.3"
    public static String xbeanClassloaderVersion = "3.7"

    public static String junit4Version = "4.12"
    public static String junit5Version = "5.1.1"
    public static String awaitilityVersion = "2.0.0"
    public static String assertjVersion = "3.7.0"
    public static String xmlunitVersion = "1.4"
    public static String mockitoVersion = "2.23.4"
    public static String jsonUnitVersion = "1.25.1"
    public static String systemRulesVersion = "1.16.0"
    public static String concurrentUnitVersion = "0.4.0"
    public static String jettyVersion = "9.4.9.v20180320"


    //Build plugins
    public static String bonitaPluginsVersion = "0.1.42"

}
