class Deps {

    public static String springVersion = "5.2.9.RELEASE"
    public static String springBootVersion = "2.3.4.RELEASE"
    public static String commonsIOVersion = "2.8.0"
    //fileupload 1.4 does not work on web-side.
    public static String commonsFileupload = "1.3.3"
    public static String commonsBeanutilsVersion = "1.9.4"
    public static String commonsCollections4Version = "4.4"
    public static String commonsLangVersion = "3.11"
    public static String commonsTextVersion = "1.9"
    public static String commonsDbcp2Version = "2.5.0"
    public static String commonsExecVersion = "1.3"
    public static String commonsCLIVersion = "1.4"
    public static String slf4jVersion = "1.7.30"
    public static String h2Version = "1.4.199"
    public static String hibernateVersion = "5.4.10.Final"
    public static String jacksonDataBindingVersion = "2.11.2"
    public static String javaxJtaVersion = "1.1"
    public static String javaxServletVersion = "3.0.1"
    public static String groovyVersion = "3.0.7"
    public static String javassistVersion = "3.18.1-GA"
    public static String httpComponentsVersion = "4.5.12"
    public static String xstreamVersion = "1.4.15"
    public static String ehcacheVersion = "2.10.6"
    public static String eclipseCompilerVersion = "3.20.0"
    public static String jbcryptVersion = "0.4"
    public static String activationVersion = "1.2.2"
    public static String quartzVersion = "2.3.2"
    public static String micrometerVersion = "1.6.1"

    public static String mysqlVersion = "8.0.14"
    public static String mssqlVersion = "8.4.1.jre8"
    public static String oracleVersion = "19.3.0.0"
    public static String postgresqlVersion = "42.2.5"
    public static String lombokVersion = "1.18.12"

    public static String narayanaVersion = "5.10.6.Final"
    public static String jbossLoggingVersion = "3.1.3.GA"
    public static String jaxbVersion = "2.3.1"
    public static String logbackVersion = "1.2.3"
    public static String xbeanClassloaderVersion = "3.7"

    public static String junit4Version = "4.13.1"
    public static String junit5Version = "5.6.3"
    public static String awaitilityVersion = "4.0.3"
    public static String assertjVersion = "3.17.2"
    public static String xmlunitVersion = "1.6"
    public static String mockitoVersion = "3.5.10"
    public static String jsonUnitVersion = "2.19.0"
    public static String systemRulesVersion = "1.19.0"
    public static String concurrentUnitVersion = "0.4.6"
    public static String junitQuickCheck = "0.9.1"
    public static String jettyVersion = "9.4.9.v20180320"
    public static String javaxAnnotationsVersion = "1.3.2"

}
