plugins {
    id "org.sonarqube" version "6.3.1.5724"
    alias(libs.plugins.taskInfo)
}

sonarqube {
    properties {
          property "sonar.projectKey", "bonitasoft_bonita-engine"
          property "sonar.organization", "bonitasoft"
          property "sonar.host.url", "https://sonarcloud.io"
    }
}

apply from: "common.gradle"
