/**
 * Copyright (C) 2026 Bonitasoft S.A.
 * Bonitasoft, 32 rue Gustave Eiffel - 38000 Grenoble
 * This library is free software; you can redistribute it and/or modify it under the terms
 * of the GNU Lesser General Public License as published by the Free Software Foundation
 * version 2.1 of the License.
 * This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Lesser General Public License for more details.
 * You should have received a copy of the GNU Lesser General Public License along with this
 * program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth
 * Floor, Boston, MA 02110-1301, USA.
 **/
package org.bonitasoft.engine.core.process.definition.model;

import lombok.Data;

/**
 * Read-only projection identifying a group of process deployment infos sharing the same
 * (name, displayName) combination. Only serves query purposes (like a view), not persisted.
 * <p>
 * The all-args constructor (generated by {@code @Data} over the final fields) matches the
 * {@code SELECT new ProcessNameKey(name, displayName)} HQL projection, and equals/hashCode (over both fields) make it
 * usable as a grouping map key.
 */
@Data
public class ProcessNameKey {

    private final String name;
    private final String displayName;
}
