CREATE TABLE process_definition (
  tenantid NUMBER(19, 0) NOT NULL,
  id NUMBER(19, 0) NOT NULL,
  processId NUMBER(19, 0) NOT NULL,
  name VARCHAR2(150) NOT NULL,
  version VARCHAR2(50) NOT NULL,
  description VARCHAR2(255),
  deploymentDate NUMBER(19, 0) NOT NULL,
  deployedBy NUMBER(19, 0) NOT NULL,
  activationState VARCHAR2(30) NOT NULL,
  configurationState VARCHAR2(30) NOT NULL,
  migrationDate NUMBER(19, 0),
  displayName VARCHAR2(75),
  displayDescription VARCHAR2(255),
  lastUpdateDate NUMBER(19, 0),
  categoryId NUMBER(19, 0),
  iconPath VARCHAR2(255),
  PRIMARY KEY (tenantid, id),
  UNIQUE (tenantid, name, version)
);
