DROP TABLE IF EXISTS QRTZ_FIRED_TRIGGERS
GO
DROP TABLE IF EXISTS QRTZ_PAUSED_TRIGGER_GRPS
GO
DROP TABLE IF EXISTS QRTZ_SCHEDULER_STATE
GO
DROP TABLE IF EXISTS QRTZ_LOCKS
GO
DROP TABLE IF EXISTS QRTZ_SIMPLE_TRIGGERS
GO
DROP TABLE IF EXISTS QRTZ_SIMPROP_TRIGGERS
GO
DROP TABLE IF EXISTS QRTZ_CRON_TRIGGERS
GO
DROP TABLE IF EXISTS QRTZ_VARBINARY(MAX)_TRIGGERS
GO
DROP TABLE IF EXISTS QRTZ_TRIGGERS
GO
DROP TABLE IF EXISTS QRTZ_JOB_DETAILS
GO
DROP TABLE IF EXISTS QRTZ_CALENDARS
GO
