package org.bonitasoft.engine.platform.model.impl;

import org.assertj.core.api.AbstractAssert;
import org.assertj.core.util.Objects;

/**
 * {@link SPlatformImpl} specific assertions - Generated by CustomAssertionGenerator.
 */
public class SPlatformImplAssert extends AbstractAssert<SPlatformImplAssert, SPlatformImpl> {

  /**
   * Creates a new <code>{@link SPlatformImplAssert}</code> to make assertions on actual SPlatformImpl.
   * @param actual the SPlatformImpl we want to make assertions on.
   */
  public SPlatformImplAssert(SPlatformImpl actual) {
    super(actual, SPlatformImplAssert.class);
  }

  /**
   * An entry point for SPlatformImplAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(mySPlatformImpl)</code> and get specific assertion with code completion.
   * @param actual the SPlatformImpl we want to make assertions on.
   * @return a new <code>{@link SPlatformImplAssert}</code>
   */
  public static SPlatformImplAssert assertThat(SPlatformImpl actual) {
    return new SPlatformImplAssert(actual);
  }

  /**
   * Verifies that the actual SPlatformImpl's created is equal to the given one.
   * @param created the given created to compare the actual SPlatformImpl's created to.
   * @return this assertion object.
   * @throws AssertionError - if the actual SPlatformImpl's created is not equal to the given one.
   */
  public SPlatformImplAssert hasCreated(long created) {
    // check that actual SPlatformImpl we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpected created of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // check
    long actualCreated = actual.getCreated();
    if (actualCreated != created) {
      failWithMessage(assertjErrorMessage, actual, created, actualCreated);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual SPlatformImpl's createdBy is equal to the given one.
   * @param createdBy the given createdBy to compare the actual SPlatformImpl's createdBy to.
   * @return this assertion object.
   * @throws AssertionError - if the actual SPlatformImpl's createdBy is not equal to the given one.
   */
  public SPlatformImplAssert hasCreatedBy(String createdBy) {
    // check that actual SPlatformImpl we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpected createdBy of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    String actualCreatedBy = actual.getCreatedBy();
    if (!Objects.areEqual(actualCreatedBy, createdBy)) {
      failWithMessage(assertjErrorMessage, actual, createdBy, actualCreatedBy);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual SPlatformImpl's discriminator is equal to the given one.
   * @param discriminator the given discriminator to compare the actual SPlatformImpl's discriminator to.
   * @return this assertion object.
   * @throws AssertionError - if the actual SPlatformImpl's discriminator is not equal to the given one.
   */
  public SPlatformImplAssert hasDiscriminator(String discriminator) {
    // check that actual SPlatformImpl we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpected discriminator of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    String actualDiscriminator = actual.getDiscriminator();
    if (!Objects.areEqual(actualDiscriminator, discriminator)) {
      failWithMessage(assertjErrorMessage, actual, discriminator, actualDiscriminator);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual SPlatformImpl's id is equal to the given one.
   * @param id the given id to compare the actual SPlatformImpl's id to.
   * @return this assertion object.
   * @throws AssertionError - if the actual SPlatformImpl's id is not equal to the given one.
   */
  public SPlatformImplAssert hasId(long id) {
    // check that actual SPlatformImpl we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpected id of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // check
    long actualId = actual.getId();
    if (actualId != id) {
      failWithMessage(assertjErrorMessage, actual, id, actualId);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual SPlatformImpl's information is equal to the given one.
   * @param information the given information to compare the actual SPlatformImpl's information to.
   * @return this assertion object.
   * @throws AssertionError - if the actual SPlatformImpl's information is not equal to the given one.
   */
  public SPlatformImplAssert hasInformation(String information) {
    // check that actual SPlatformImpl we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpected information of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    String actualInformation = actual.getInformation();
    if (!Objects.areEqual(actualInformation, information)) {
      failWithMessage(assertjErrorMessage, actual, information, actualInformation);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual SPlatformImpl's initialVersion is equal to the given one.
   * @param initialVersion the given initialVersion to compare the actual SPlatformImpl's initialVersion to.
   * @return this assertion object.
   * @throws AssertionError - if the actual SPlatformImpl's initialVersion is not equal to the given one.
   */
  public SPlatformImplAssert hasInitialVersion(String initialVersion) {
    // check that actual SPlatformImpl we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpected initialVersion of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    String actualInitialVersion = actual.getInitialVersion();
    if (!Objects.areEqual(actualInitialVersion, initialVersion)) {
      failWithMessage(assertjErrorMessage, actual, initialVersion, actualInitialVersion);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual SPlatformImpl's previousVersion is equal to the given one.
   * @param previousVersion the given previousVersion to compare the actual SPlatformImpl's previousVersion to.
   * @return this assertion object.
   * @throws AssertionError - if the actual SPlatformImpl's previousVersion is not equal to the given one.
   */
  public SPlatformImplAssert hasPreviousVersion(String previousVersion) {
    // check that actual SPlatformImpl we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpected previousVersion of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    String actualPreviousVersion = actual.getPreviousVersion();
    if (!Objects.areEqual(actualPreviousVersion, previousVersion)) {
      failWithMessage(assertjErrorMessage, actual, previousVersion, actualPreviousVersion);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual SPlatformImpl's tenantId is equal to the given one.
   * @param tenantId the given tenantId to compare the actual SPlatformImpl's tenantId to.
   * @return this assertion object.
   * @throws AssertionError - if the actual SPlatformImpl's tenantId is not equal to the given one.
   */
  public SPlatformImplAssert hasTenantId(long tenantId) {
    // check that actual SPlatformImpl we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpected tenantId of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // check
    long actualTenantId = actual.getTenantId();
    if (actualTenantId != tenantId) {
      failWithMessage(assertjErrorMessage, actual, tenantId, actualTenantId);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual SPlatformImpl's version is equal to the given one.
   * @param version the given version to compare the actual SPlatformImpl's version to.
   * @return this assertion object.
   * @throws AssertionError - if the actual SPlatformImpl's version is not equal to the given one.
   */
  public SPlatformImplAssert hasVersion(String version) {
    // check that actual SPlatformImpl we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpected version of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    String actualVersion = actual.getVersion();
    if (!Objects.areEqual(actualVersion, version)) {
      failWithMessage(assertjErrorMessage, actual, version, actualVersion);
    }

    // return the current assertion for method chaining
    return this;
  }

}
