package org.bonitasoft.engine.business.application.model.impl;

import org.assertj.core.api.AbstractAssert;
import org.assertj.core.util.Objects;

/**
 * {@link SApplicationImpl} specific assertions - Generated by CustomAssertionGenerator.
 */
public class SApplicationImplAssert extends AbstractAssert<SApplicationImplAssert, SApplicationImpl> {

  /**
   * Creates a new <code>{@link SApplicationImplAssert}</code> to make assertions on actual SApplicationImpl.
   * @param actual the SApplicationImpl we want to make assertions on.
   */
  public SApplicationImplAssert(SApplicationImpl actual) {
    super(actual, SApplicationImplAssert.class);
  }

  /**
   * An entry point for SApplicationImplAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(mySApplicationImpl)</code> and get specific assertion with code completion.
   * @param actual the SApplicationImpl we want to make assertions on.
   * @return a new <code>{@link SApplicationImplAssert}</code>
   */
  public static SApplicationImplAssert assertThat(SApplicationImpl actual) {
    return new SApplicationImplAssert(actual);
  }

  /**
   * Verifies that the actual SApplicationImpl's createdBy is equal to the given one.
   * @param createdBy the given createdBy to compare the actual SApplicationImpl's createdBy to.
   * @return this assertion object.
   * @throws AssertionError - if the actual SApplicationImpl's createdBy is not equal to the given one.
   */
  public SApplicationImplAssert hasCreatedBy(long createdBy) {
    // check that actual SApplicationImpl we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpected createdBy of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // check
    long actualCreatedBy = actual.getCreatedBy();
    if (actualCreatedBy != createdBy) {
      failWithMessage(assertjErrorMessage, actual, createdBy, actualCreatedBy);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual SApplicationImpl's creationDate is equal to the given one.
   * @param creationDate the given creationDate to compare the actual SApplicationImpl's creationDate to.
   * @return this assertion object.
   * @throws AssertionError - if the actual SApplicationImpl's creationDate is not equal to the given one.
   */
  public SApplicationImplAssert hasCreationDate(long creationDate) {
    // check that actual SApplicationImpl we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpected creationDate of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // check
    long actualCreationDate = actual.getCreationDate();
    if (actualCreationDate != creationDate) {
      failWithMessage(assertjErrorMessage, actual, creationDate, actualCreationDate);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual SApplicationImpl's description is equal to the given one.
   * @param description the given description to compare the actual SApplicationImpl's description to.
   * @return this assertion object.
   * @throws AssertionError - if the actual SApplicationImpl's description is not equal to the given one.
   */
  public SApplicationImplAssert hasDescription(String description) {
    // check that actual SApplicationImpl we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpected description of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    String actualDescription = actual.getDescription();
    if (!Objects.areEqual(actualDescription, description)) {
      failWithMessage(assertjErrorMessage, actual, description, actualDescription);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual SApplicationImpl's discriminator is equal to the given one.
   * @param discriminator the given discriminator to compare the actual SApplicationImpl's discriminator to.
   * @return this assertion object.
   * @throws AssertionError - if the actual SApplicationImpl's discriminator is not equal to the given one.
   */
  public SApplicationImplAssert hasDiscriminator(String discriminator) {
    // check that actual SApplicationImpl we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpected discriminator of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    String actualDiscriminator = actual.getDiscriminator();
    if (!Objects.areEqual(actualDiscriminator, discriminator)) {
      failWithMessage(assertjErrorMessage, actual, discriminator, actualDiscriminator);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual SApplicationImpl's displayName is equal to the given one.
   * @param displayName the given displayName to compare the actual SApplicationImpl's displayName to.
   * @return this assertion object.
   * @throws AssertionError - if the actual SApplicationImpl's displayName is not equal to the given one.
   */
  public SApplicationImplAssert hasDisplayName(String displayName) {
    // check that actual SApplicationImpl we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpected displayName of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    String actualDisplayName = actual.getDisplayName();
    if (!Objects.areEqual(actualDisplayName, displayName)) {
      failWithMessage(assertjErrorMessage, actual, displayName, actualDisplayName);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual SApplicationImpl's homePageId is equal to the given one.
   * @param homePageId the given homePageId to compare the actual SApplicationImpl's homePageId to.
   * @return this assertion object.
   * @throws AssertionError - if the actual SApplicationImpl's homePageId is not equal to the given one.
   */
  public SApplicationImplAssert hasHomePageId(Long homePageId) {
    // check that actual SApplicationImpl we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpected homePageId of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    Long actualHomePageId = actual.getHomePageId();
    if (!Objects.areEqual(actualHomePageId, homePageId)) {
      failWithMessage(assertjErrorMessage, actual, homePageId, actualHomePageId);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual SApplicationImpl's iconPath is equal to the given one.
   * @param iconPath the given iconPath to compare the actual SApplicationImpl's iconPath to.
   * @return this assertion object.
   * @throws AssertionError - if the actual SApplicationImpl's iconPath is not equal to the given one.
   */
  public SApplicationImplAssert hasIconPath(String iconPath) {
    // check that actual SApplicationImpl we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpected iconPath of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    String actualIconPath = actual.getIconPath();
    if (!Objects.areEqual(actualIconPath, iconPath)) {
      failWithMessage(assertjErrorMessage, actual, iconPath, actualIconPath);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual SApplicationImpl's id is equal to the given one.
   * @param id the given id to compare the actual SApplicationImpl's id to.
   * @return this assertion object.
   * @throws AssertionError - if the actual SApplicationImpl's id is not equal to the given one.
   */
  public SApplicationImplAssert hasId(long id) {
    // check that actual SApplicationImpl we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpected id of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // check
    long actualId = actual.getId();
    if (actualId != id) {
      failWithMessage(assertjErrorMessage, actual, id, actualId);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual SApplicationImpl's lastUpdateDate is equal to the given one.
   * @param lastUpdateDate the given lastUpdateDate to compare the actual SApplicationImpl's lastUpdateDate to.
   * @return this assertion object.
   * @throws AssertionError - if the actual SApplicationImpl's lastUpdateDate is not equal to the given one.
   */
  public SApplicationImplAssert hasLastUpdateDate(long lastUpdateDate) {
    // check that actual SApplicationImpl we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpected lastUpdateDate of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // check
    long actualLastUpdateDate = actual.getLastUpdateDate();
    if (actualLastUpdateDate != lastUpdateDate) {
      failWithMessage(assertjErrorMessage, actual, lastUpdateDate, actualLastUpdateDate);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual SApplicationImpl's layoutId is equal to the given one.
   * @param layoutId the given layoutId to compare the actual SApplicationImpl's layoutId to.
   * @return this assertion object.
   * @throws AssertionError - if the actual SApplicationImpl's layoutId is not equal to the given one.
   */
  public SApplicationImplAssert hasLayoutId(Long layoutId) {
    // check that actual SApplicationImpl we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpected layoutId of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    Long actualLayoutId = actual.getLayoutId();
    if (!Objects.areEqual(actualLayoutId, layoutId)) {
      failWithMessage(assertjErrorMessage, actual, layoutId, actualLayoutId);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual SApplicationImpl's profileId is equal to the given one.
   * @param profileId the given profileId to compare the actual SApplicationImpl's profileId to.
   * @return this assertion object.
   * @throws AssertionError - if the actual SApplicationImpl's profileId is not equal to the given one.
   */
  public SApplicationImplAssert hasProfileId(Long profileId) {
    // check that actual SApplicationImpl we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpected profileId of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    Long actualProfileId = actual.getProfileId();
    if (!Objects.areEqual(actualProfileId, profileId)) {
      failWithMessage(assertjErrorMessage, actual, profileId, actualProfileId);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual SApplicationImpl's state is equal to the given one.
   * @param state the given state to compare the actual SApplicationImpl's state to.
   * @return this assertion object.
   * @throws AssertionError - if the actual SApplicationImpl's state is not equal to the given one.
   */
  public SApplicationImplAssert hasState(String state) {
    // check that actual SApplicationImpl we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpected state of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    String actualState = actual.getState();
    if (!Objects.areEqual(actualState, state)) {
      failWithMessage(assertjErrorMessage, actual, state, actualState);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual SApplicationImpl's tenantId is equal to the given one.
   * @param tenantId the given tenantId to compare the actual SApplicationImpl's tenantId to.
   * @return this assertion object.
   * @throws AssertionError - if the actual SApplicationImpl's tenantId is not equal to the given one.
   */
  public SApplicationImplAssert hasTenantId(long tenantId) {
    // check that actual SApplicationImpl we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpected tenantId of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // check
    long actualTenantId = actual.getTenantId();
    if (actualTenantId != tenantId) {
      failWithMessage(assertjErrorMessage, actual, tenantId, actualTenantId);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual SApplicationImpl's themeId is equal to the given one.
   * @param themeId the given themeId to compare the actual SApplicationImpl's themeId to.
   * @return this assertion object.
   * @throws AssertionError - if the actual SApplicationImpl's themeId is not equal to the given one.
   */
  public SApplicationImplAssert hasThemeId(Long themeId) {
    // check that actual SApplicationImpl we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpected themeId of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    Long actualThemeId = actual.getThemeId();
    if (!Objects.areEqual(actualThemeId, themeId)) {
      failWithMessage(assertjErrorMessage, actual, themeId, actualThemeId);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual SApplicationImpl's token is equal to the given one.
   * @param token the given token to compare the actual SApplicationImpl's token to.
   * @return this assertion object.
   * @throws AssertionError - if the actual SApplicationImpl's token is not equal to the given one.
   */
  public SApplicationImplAssert hasToken(String token) {
    // check that actual SApplicationImpl we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpected token of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    String actualToken = actual.getToken();
    if (!Objects.areEqual(actualToken, token)) {
      failWithMessage(assertjErrorMessage, actual, token, actualToken);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual SApplicationImpl's updatedBy is equal to the given one.
   * @param updatedBy the given updatedBy to compare the actual SApplicationImpl's updatedBy to.
   * @return this assertion object.
   * @throws AssertionError - if the actual SApplicationImpl's updatedBy is not equal to the given one.
   */
  public SApplicationImplAssert hasUpdatedBy(long updatedBy) {
    // check that actual SApplicationImpl we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpected updatedBy of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // check
    long actualUpdatedBy = actual.getUpdatedBy();
    if (actualUpdatedBy != updatedBy) {
      failWithMessage(assertjErrorMessage, actual, updatedBy, actualUpdatedBy);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual SApplicationImpl's version is equal to the given one.
   * @param version the given version to compare the actual SApplicationImpl's version to.
   * @return this assertion object.
   * @throws AssertionError - if the actual SApplicationImpl's version is not equal to the given one.
   */
  public SApplicationImplAssert hasVersion(String version) {
    // check that actual SApplicationImpl we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpected version of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    String actualVersion = actual.getVersion();
    if (!Objects.areEqual(actualVersion, version)) {
      failWithMessage(assertjErrorMessage, actual, version, actualVersion);
    }

    // return the current assertion for method chaining
    return this;
  }

}
