plugins {
    id("me.champeau.jmh") version "0.7.3"
}

dependencies {
    api libs.assertj
    api libs.mockitoCore
    api project(':bonita-integration-tests:bonita-integration-tests-client')
    api project(':bpm:bonita-server')
    testRuntimeOnly libs.logback
}

jmh {
    duplicateClassesStrategy = DuplicatesStrategy.WARN
    iterations = 2
    threads = 1
    fork = 1
}