s/DEFAULT FALSE/DEFAULT 0/g
s/LONGVARBINARY/VARBINARY(MAX)/g
s/LONGVARCHAR/NVARCHAR(MAX)/g
s/BOOLEAN/BIT/g
s/BIGINT/NUMERIC(19, 0)/g
s/IMAGE/VARBINARY(MAX)/g
s/LONGBLOB/VARBINARY(MAX)/g
s/MEDIUMBLOB/VARBINARY(MAX)/g
s/BLOB/VARBINARY(MAX)/g
s/CLOB/NVARCHAR(MAX)/g
s/TEXT/NVARCHAR(MAX)/g
s/ VARCHAR/ NVARCHAR/g
s/;/\nGO/g
