s/DEFAULT FALSE/DEFAULT 0/g
s/LONGVARBINARY/VARBINARY(MAX)/g
s/LONGVARCHAR/VARCHAR(MAX)/g
s/BOOLEAN/BIT/g
s/BIGINT/NUMERIC(19, 0)/g
s/IMAGE/VARBINARY(MAX)/g
s/BLOB/VARBINARY(MAX)/g
s/CLOB/VARCHAR(MAX)/g
s/LONG/NUMERIC(19, 0)/g
s/TEXT/VARCHAR(MAX)/g
s/;/\nGO/g
