dependencies {
    api project(':services:bonita-cache')
    api project(':services:bonita-builder')
    api project(':services:bonita-persistence')
    api project(':services:bonita-commons')
    testImplementation project(':services:bonita-events')
    testImplementation(libs.mockitoCore)
    testImplementation(libs.assertj)
    testImplementation(libs.logback)

    annotationProcessor(libs.lombok)
    compileOnly(libs.lombok)
}

group = 'org.bonitasoft.engine.platform'

def generatePlatformProperties = tasks.register("generatePlatformProperties") {
    def outputDir = layout.buildDirectory.dir("generated/main/resources/org/bonitasoft/engine/platform/model/impl")
    def outputFile = layout.buildDirectory.file("generated/main/resources/org/bonitasoft/engine/platform/model/impl/platform.properties")
    def projectVersion = project.version

    doFirst{
        outputDir.get().asFile.mkdirs()
        outputFile.get().asFile.text = "version $projectVersion"
    }
    inputs.property "version", projectVersion
    outputs.file outputFile
}
tasks.processResources.dependsOn generatePlatformProperties
sourceSets {
    main {
        resources {
            srcDir(layout.buildDirectory.dir("generated/main/resources"))
        }
    }
}
